import { listChannelPlugins } from "../channels/plugins/index.js";

const BASE_METHODS = [
  "health",
  "logs.tail",
  "channels.status",
  "channels.logout",
  "status",
  "usage.status",
  "usage.cost",
  "tts.status",
  "tts.providers",
  "tts.enable",
  "tts.disable",
  "tts.convert",
  "tts.setProvider",
  "config.get",
  "config.set",
  "config.apply",
  "config.patch",
  "config.schema",
  "exec.approvals.get",
  "exec.approvals.set",
  "exec.approvals.node.get",
  "exec.approvals.node.set",
  "exec.approval.request",
  "exec.approval.resolve",
  "wizard.start",
  "wizard.next",
  "wizard.cancel",
  "wizard.status",
  "talk.mode",
  "models.list",
  "agents.list",
  "skills.status",
  "skills.bins",
  "skills.install",
  "skills.update",
  "update.run",
  "voicewake.get",
  "voicewake.set",
  "sessions.list",
  "sessions.preview",
  "sessions.patch",
  "sessions.reset",
  "sessions.delete",
  "sessions.compact",
  "last-heartbeat",
  "set-heartbeats",
  "wake",
  "node.pair.request",
  "node.pair.list",
  "node.pair.approve",
  "node.pair.reject",
  "node.pair.verify",
  "device.pair.list",
  "device.pair.approve",
  "device.pair.reject",
  "device.token.rotate",
  "device.token.revoke",
  "node.rename",
  "node.list",
  "node.describe",
  "node.invoke",
  "node.invoke.result",
  "node.event",
  "cron.list",
  "cron.status",
  "cron.add",
  "cron.update",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "system-presence",
  "system-event",
  "send",
  "agent",
  "agent.identity.get",
  "agent.wait",
  "browser.request",
  // Pi optimization methods
  "pi.getMetrics",
  "pi.getConfiguration", 
  "pi.getStatus",
  "pi.getRecentEvents",
  "pi.triggerOptimization",
  "pi.getResourceHistory",
  // Pi messaging optimization methods
  "pi.messaging.getNetworkMetrics",
  "pi.messaging.getQueueStatus",
  "pi.messaging.retryQueuedMessages",
  "pi.messaging.optimizeChannel",
  "pi.messaging.queueMessage",
  // Pi media optimization methods
  "pi.media.getMetrics",
  "pi.media.getCacheStats",
  "pi.media.getExternalStoragePaths",
  "pi.media.getOptimalStorageLocation",
  "pi.media.processFile",
  "pi.media.createMemoryMappedFile",
  // Pi AI agent optimization methods
  "pi.agent.getMetrics",
  "pi.agent.getQueueStatus",
  "pi.agent.queueExecution",
  "pi.agent.getOptimizationRecommendations",
  "pi.agent.cancelExecution",
  // WebChat WebSocket-native chat methods
  "chat.history",
  "chat.abort",
  "chat.send",
];

export function listGatewayMethods(): string[] {
  const channelMethods = listChannelPlugins().flatMap((plugin) => plugin.gatewayMethods ?? []);
  return Array.from(new Set([...BASE_METHODS, ...channelMethods]));
}

export const GATEWAY_EVENTS = [
  "connect.challenge",
  "agent",
  "chat",
  "presence",
  "tick",
  "talk.mode",
  "shutdown",
  "health",
  "heartbeat",
  "cron",
  "node.pair.requested",
  "node.pair.resolved",
  "node.invoke.request",
  "device.pair.requested",
  "device.pair.resolved",
  "voicewake.changed",
  "exec.approval.requested",
  "exec.approval.resolved",
  // Pi optimization events
  "pi.metrics.update",
  "pi.event.occurred",
  "pi.status.changed",
  "pi.optimization.completed",
  // Pi messaging optimization events
  "pi.messaging.messageQueued",
  "pi.messaging.messageProcessed",
  "pi.messaging.messageExpired",
  "pi.messaging.connectivityRestored",
  "pi.messaging.connectivityLost",
  "pi.messaging.statusChanged",
  "pi.messaging.error",
  // Pi media optimization events
  "pi.media.fileProcessed",
  "pi.media.memoryMappedFileCreated",
  "pi.media.statusChanged",
  "pi.media.error",
  // Pi AI agent optimization events
  "pi.agent.queued",
  "pi.agent.started",
  "pi.agent.completed",
  "pi.agent.cancelled",
  "pi.agent.resourcePressure",
  "pi.agent.thermalThrottling",
  "pi.agent.thermalRecovery",
  "pi.agent.statusChanged",
  "pi.agent.error",
];
